name: Generate Pydoc

on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Loading repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Do not fail if pylint
      - name: Run pylint
        run: |
          pip install pylint
          pylint --exit-zero --disable=C0115,C0116,C0301 $(git ls-files '*.py') || true

      # 4. Pydoc documentation generating
      - name: Generate docs with pydoc
        run: |
          set -e
          mkdir -p docs
          for f in $(git ls-files '*.py'); do
            module=${f%.py}
            module=${module//\//.}
            echo Generating docs for "$module"
            python -m pydoc -w "$module"
          done
          mv ./*.html docs/

      # 5. To see html after run
      - name: Upload pydoc HTML
        uses: actions/upload-artifact@v4
        with:
          name: pydoc-html
          path: docs/
          
      # 6. Build Docker image (packaging)
      - name: Build Docker image
        run: docker build -t logging-app-demo .

      # 7. Run Docker container (deploy smoke test)
      - name: Run Docker container (smoke test)
        run: docker run --rm logging-app-demo
